FROM python:3.10-slim
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt --no-cache-dir
RUN python3 manage.py migrate
RUN python3 manage.py load_csv
RUN python3 manage.py collectstatic

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "config.wsgi", "--timeout", "0"]
