# Generated by Django 4.2.7 on 2023-11-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_key', models.CharField(max_length=100, verbose_name='Номер позиции')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('product_url', models.CharField(max_length=100, verbose_name='Адрес получения данных')),
                ('product_name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата получения данных')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dealer', verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'С площадок дилера',
                'verbose_name_plural': 'С площадок дилеров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('ean_13', models.CharField(max_length=100, verbose_name='EAN-13')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('min_recommended_price', models.FloatField(verbose_name='Минимальная рекомендованная цена')),
                ('recommended_price', models.FloatField(verbose_name='Рекомендованная цена')),
                ('category_id', models.FloatField(verbose_name='Id категории')),
                ('ozon_name', models.CharField(max_length=100, verbose_name='Название Озон')),
                ('name_1c', models.CharField(max_length=100, verbose_name='Название 1С')),
                ('wb_name', models.CharField(max_length=100, verbose_name='Название WB')),
                ('ozon_article', models.CharField(max_length=100, verbose_name='Описание Озон')),
                ('wb_article', models.CharField(max_length=100, verbose_name='Артикул WB')),
                ('ym_article', models.CharField(max_length=100, verbose_name='Артикул Я.Маркет')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dealer')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dealerprice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Продукт дилера',
                'verbose_name_plural': 'Продукты дилеров',
            },
        ),
    ]
