# Generated by Django 4.2.7 on 2023-12-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdealer',
            options={'default_related_name': 'matches', 'verbose_name': 'Продукт дилера', 'verbose_name_plural': 'Продукты дилеров'},
        ),
        migrations.RemoveConstraint(
            model_name='dealerprice',
            name='unique_ingredient',
        ),
        migrations.AlterField(
            model_name='productdealer',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dealerprice'),
        ),
    ]
