# Generated by Django 4.2.7 on 2023-12-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productdealer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdealer',
            options={'verbose_name': 'Продукт дилера', 'verbose_name_plural': 'Продукты дилеров'},
        ),
        migrations.AlterField(
            model_name='productdealer',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='products.dealerprice'),
        ),
        migrations.AddConstraint(
            model_name='productdealer',
            constraint=models.UniqueConstraint(fields=('key', 'dealer', 'product'), name='unique_dealer_product_key'),
        ),
    ]
