# Generated by Django 4.2.7 on 2023-12-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_dealer_name_alter_dealerprice_product_key_and_more'),
        ('products', '0003_alter_productdealer_options_alter_productdealer_key_and_more'),
    ]

    operations = [
    ]
